# Generated by Django 5.1 on 2024-08-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Registration',
            },
        ),
    ]
