# Generated by Django 5.1 on 2024-08-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_positions_candidate_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, default='static/profiles/default.png', null=True, upload_to='static/profiles/'),
        ),
    ]
