# Generated by Django 5.1 on 2024-08-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
